# Generated by Django 3.0.7 on 2020-06-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200623_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
